### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by jaikishantulswani** [g147/g147.github.io#1]
@g147 whats you twitter handle ?

**Comment by g147** [comment]
no twitter. @beastglatisant - telegram

**Comment by jaikishantulswani** [comment]
@g147 why not on twitter ?

**Comment by g147** [comment]
it was getting kinda addictive. i stay away from addictions. & yeah im not maintaining huntdb anymore. the repo to which i invited you was the most recent & last version.

**Comment by jaikishantulswani** [comment]
@g147 so now on which you are working similar to huntdb , like what happen and why this project is not maintained anymore.

**Comment by g147** [comment]
that project didn't seem profitable currently & there are already wider coverage services like spyse. so i figured if i use my resources to do the same thing but for enterprise clients then it would be profitable. & as not much people from the so called community seem interested, i moved on from doing probono stuffs. its was flop idea anyway. there seem no point to me in raining over an ocean.
